version: "3"
services:
  miniconda:
    build: . 
    container_name: "miniconda"
    ports:
      - "2222:22" 
    volumes:
      - .:/code
    working_dir: /code
    command: /bin/bash -c "tail -f /dev/null"
    entrypoint: ""
